### ISSUE TITLE
Cannot set property message of [object DOMException] which has only a getter

### ISSUE THREAD

**Issue by vaclavGabriel** [testing-library/cypress-testing-library#206]
**Versions:**
- `cypress-testing-library` version: 8.0.1
- `node` version: 12.22.6
- `npm` version: 6.14.15

**What you did:** I tried to get an element using the `cy.findByRole` command

**What happened:**
`TypeError: Cannot set property message of [object DOMException] which has only a getter`

```javascript
TypeError: Cannot set property message of [object DOMException] which has only a getter
    at modifyErrMsg (http://localhost:3002/__cypress/runner/cypress_runner.js:172545:15)
    at $Cy.retry (http://localhost:3002/__cypress/runner/cypress_runner.js:164808:33)
    at onFailFn (http://localhost:3002/__cypress/runner/cypress_runner.js:148305:21)
From previous event:
    at $Cy.verifyUpcomingAssertions (http://localhost:3002/__cypress/runner/cypress_runner.js:148312:105)
From previous event:
    at tryFn (http://localhost:3002/__cypress/runner/cypress_runner.js:165332:61)
    at whenStable (http://localhost:3002/__cypress/runner/cypress_runner.js:165371:14)
    at http://localhost:3002/__cypress/runner/cypress_runner.js:164858:18
```

![image](https://user-images.githubusercontent.com/48252269/139446740-09d6e42b-29ce-4790-97e0-80a64a00302d.png)

**Problem description:** I am getting the error above when using `findByRole` from Cypress Testing Library

**Suggested solution:** Rollback to the version 7.0.7 helps

**Comment by MAfzalKhan1997** [comment]
any update on above issue ?

**Comment by MathiasCarranza04** [comment]
I'm having the same issue

**Comment by nilesh-powar-InfoTrack** [comment]
same here 😢

**Comment by schester44** [comment]
seeing this as well when using react-app-rewired and craco with a create react app application. very strange.

**Comment by RuudMeeuwsen** [comment]
I had the same issue. I rolled back to v7.0.7, which indeed solves it, but of course I'd rather use the latest version.
It doesn't look like there's much developer activity here, though :(

**Comment by oussbenma** [comment]
Same issue discovered with this Cypress version:

Cypress package version: 12.2.0
Cypress binary version: 12.2.0
Electron version: 21.0.0
Bundled Node version: 16.16.0

**Comment by darryl-mtrs** [comment]
Still encounter this issue today,
I have two blocks of test, the error always shows up at the second block.

so I removed all the test and found that:
1. _describe('Description', () => {})_ => works fine
2. _describe('Description', () => {
         it('should works fine', () => {})
    })_ => failed with the above error

Still not sure what is blocking my way

**Comment by darrylsepeda** [comment]
Still encounter this issue today.
so I removed all the test and found:

1. _describe('Description', () => {})_ => this works fine
2. _describe('Description', () => {
       it('should works fine', () => {})
    })_ => this is failed with the above error

Still not sure what is blocking this test

**Comment by setage** [comment]
Having this issue in Firefox, but in Electron it works fine:

Cypress 12.17.4 
Firefox 117.0.1
Electron 106

**Comment by JakubAdapt** [comment]
Same issue when upgrading from @testing-library/react: 14.1.2 to higher.

**Comment by PaulSender** [comment]
Bump. Same issue still happening Cypress: 13.15.2

Just trying to run `cy.wait(10000)` in a custom command defined in e2e.ts
