### ISSUE TITLE
any `find*` command fails when is the first to run in a test context

### ISSUE THREAD

**Issue by nickbreaton** [testing-library/cypress-testing-library#253]
- `cypress-testing-library` version: 9.0.0
- `node` version: 19.4.0
- `npm` (or `yarn`) version: 9.2.0 (npm)

What you did:

> I was migrating from an older version of testing library where we have a Cypress test set up with a describe option of `{ testIsolation: false }`, a `before` block, two `it` blocks, with the second `it` block beginning with a `find*` command.

What happened:

> When the second `it` block ran, the following error was produced:
> ```
>   TypeError: Cannot read properties of undefined (reading 'get')
>      at $Command.command (webpack:///./src/index.js:40:29)
>   From previous event:
>      at CommandQueue.runCommand (http://localhost:50133/__cypress/runner/cypress_runner.js:149951:8)
>      at next (http://localhost:50133/__cypress/runner/cypress_runner.js:150151:19)
>   ```

Reproduction repository:

> I've opened forked this repo with a quick fix for the issue, including a [reproduction via your test suite](https://github.com/testing-library/cypress-testing-library/commit/46ec754775ad47b3bdb099b71c5c81637a84d6da). 

Problem description:

> It appears in this very specific circumstance, `this.get('prev')` can yield `undefined` making the following `.get` fail. 

Suggested solution:

> Add a nullish check before accessing the second `.get`. See forked repo's [commit](https://github.com/testing-library/cypress-testing-library/commit/fdc2f0dfe813e9bac2e53175e19e6aff7d5de03e).

---

Thanks for continuing to provide an amazing utility. 🙏

**Comment by nickbreaton** [comment]
I'm happy to PR the fix I've made in my fork, including the tests if desired.

**Comment by Etzix** [comment]
I ran into this today. Thank you for finding and providing a solution :smile:

**Comment by alex1701c** [comment]
I also ran into this issue. Thanks for the explanation & workaround! A MR would be appreciated :)

**Comment by jemilox** [comment]
```
beforeEach(() => {
    cy.then(() => null)
})
```
I put this in my e2e.ts file and it worked!

**Comment by dannyskoog** [comment]
Any plans to release a fix for this? Thanks!
