### ISSUE TITLE
Dependency problem on @testing-library/dom between @testing-library/react and cypress-testing-library

### ISSUE THREAD

**Issue by gvaatstra** [testing-library/cypress-testing-library#255]
- `cypress-testing-library` version: 9.0.0
- `node` version: v18.14.1
- `npm` (or `yarn`) version: 8.17.0

Dependencies on @testing-library/dom

(base) ➜  repo git:(cypress-init) npm ls @testing-library/dom
repo@1.2.3 /x/x/workspace/repo
├─┬ @testing-library/cypress@9.0.0
│ └── @testing-library/dom@8.20.0
├─┬ @testing-library/react@14.0.0
│ └── @testing-library/dom@9.0.0
└─┬ @testing-library/user-event@14.4.3
  └── @testing-library/dom@9.0.0 deduped

This results in a 9.0.0 in my package-lock.json

```json
    "node_modules/@testing-library/dom": {
      "version": "9.0.0",
      "dev": true,
      "license": "MIT",
      "dependencies": {
....
      },
      "engines": {
        "node": ">=14"
      }
    },
```

What you did:
1. **With version 9.0.0 I get webpack errors:**

```
Error: Webpack Compilation Error
./node_modules/@testing-library/dom/dist/queries/role.js 139:59
Module parse failed: Unexpected token (139:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function makeRoleSelector(role) {
|   const explicitRoleSelector = `*[role~="${role}"]`;
>   const roleRelations = _ariaQuery.roleElements.get(role) ?? new Set();
|   const implicitRoleSelectors = new Set(Array.from(roleRelations).map(({
|     name
 @ ./node_modules/@testing-library/dom/dist/queries/index.js 72:12-29
 @ ./node_modules/@testing-library/dom/dist/index.js
 @ ./node_modules/@testing-library/cypress/dist/index.js
 @ ./node_modules/@testing-library/cypress/dist/add-commands.js
 @ ./node_modules/@testing-library/cypress/add-commands.js
 @ ./cypress/support/e2e.ts
    at Watching.handle [as handler] (/Users/gerwinvaatstra/Library/Caches/Cypress/12.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
```

2. If I manually install @testing-library/dom version 8.20.0, the unittests still seem to work and Cypress starts as well. However, that would go against the specification of @testing-library/react which needs ^9.0.0

Problem description:
Clashing dependencies. 

Suggested solution:
Upgrade to the use of 9.0.0 of @testing-library/dom, although of course as tried, it isn't as simple as upping the number because it doesn't work with 9. My knowledge is limited in what is needed to be able to work with 9.0.0

**Comment by tgdevereux** [comment]
Is this dependency update likely to be implemented soon in this library? This is causing webpack errors/build issues in any UI that we have Cypress tests implemented in, and any workaround is sub-optimal

**Comment by alexeyr-ci2** [comment]
I have the same issue with `@testing-library/cypress@10.0.3` and `@testing-library/dom@10.4.0`.

**Comment by Jorge-Cano-NS** [comment]
I'm getting the same issue as alexyr, I'm seeing it with the following versions:

- `@testing-library/cypress@10.0.3`
- `@testing-library/dom@10.4.0`
- `cypress@14.4.0`
```
Error: Parsing file [PROJECT_PATH]/node_modules/@testing-library/dom/dist/queries/role.js: Unexpected token (153:23)
    at Deps.parseDeps ([PROJECT_PATH]/node_modules/module-deps/index.js:519:15)
    at getDeps ([PROJECT_PATH]/node_modules/module-deps/index.js:447:44)
    at [PROJECT_PATH]/node_modules/module-deps/index.js:430:38
    at ConcatStream.<anonymous> ([PROJECT_PATH]/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (node:events:530:35)
    at ConcatStream.emit (node:domain:488:12)
    at finishMaybe ([PROJECT_PATH]/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable ([PROJECT_PATH]/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end ([PROJECT_PATH]/node_modules/readable-stream/lib/_stream_writable.js:594:22)
    at DuplexWrapper.onend ([PROJECT_PATH]/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:632:28)
    at DuplexWrapper.emit (node:events:530:35)
    at DuplexWrapper.emit (node:domain:488:12)
    at endReadableNT ([PROJECT_PATH]/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Digging a little into that role.js file on the error, it looks like it is this one https://github.com/testing-library/dom-testing-library/blob/a86c54ccda5242ad8dfc1c70d31980bdbf96af7f/src/queries/role.ts#L244 and it seems that the &&= operator is what cypress has an issue with.
